
```{r}
#install.packages("stplanr")
library(stplanr)
library(dplyr)
library(rgdal)
library(sf)
library(tidyverse)
library(pct)
library(tmap)
library(sp)
library(tmap)
library(ggplot2)
```

```{r}
rm (list=ls( ))
getwd()
```


```{r}
#Saving  my API token to R environment
mytoken = 'd6fee7f1acac5c7c'
Sys.setenv(CYCLESTREET = mytoken)
```

```{r}
#Load liv shape
boundary <- st_read("LCR_Boundary.shp")
```

```{r}
#Step 1 Load od and centroids
# Load OD table for all UK
OD_UK <- pct::get_od()
#Add LCR zone polygon with pct tool
liv_shape <- pct_regions[pct_regions$region_name=="liverpool-city-region", ]
#load MSOA centroids
centroids <- get_centroids_ew()
#set the same coordinates system
centroids = st_transform(centroids, st_crs(liv_shape))
#clip centroids for LCR
centroids.lcr <- centroids[liv_shape, ]
#filter flows within the lcr from the od uk
#od.LCR <- OD_UK %>%
 # filter(geo_code1 %in% centroids.lcr$msoa11cd)%>%
  #filter(geo_code2 %in% centroids.lcr$msoa11cd)
##filter flows from the od uk to only flows within the lcr 
od.LCR = OD_UK[
  OD_UK$geo_code1 %in% centroids.lcr$msoa11cd &
  OD_UK$geo_code2 %in% centroids.lcr$msoa11cd , ]
```

```{r}
#Step 2 create desire lines
#create desire lines for LCR
lines.lcr <- od2line(od.LCR, centroids.lcr)
nrow(lines.lcr)
#create inter regional flows
lines.inter <- lines.lcr %>% filter(geo_code1 != geo_code2)
nrow(lines.inter)
#create intra regional
lines.intra <- lines.lcr %>% filter(geo_code1 == geo_code2)
nrow(lines.intra)
```

### create a regional map of flows
```{r}
#Step 3
#To avoid plotting 26000 lines we need to subset
#select top all flows the mean is 15.9 and max is 722
#define minimum trips for inter flows
top.all <- lines.inter %>% filter (all >= 100)
nrow(top.all)
```

```{r}
summary(lines.inter$all)
nrow(lines.inter)
```


```{r}
#lwd = top.all$all / mean(top.$all)/10
#Create visualization
tm_shape(liv_shape)+tm_borders()+tm_fill()+
  tm_shape(top.all)+
  tm_lines(palette = "viridis", breaks = c(100,200,350,500,750),
    lwd = "all",
    scale = 8,
    title.lwd = "Number of trips",
    alpha = 0.5,
    col = "all",
    title = "Total commutes",
    legend.lwd.show = FALSE)+
    tm_scale_bar(size=.4, width = 0.15, position = c("left", "bottom")) +
  tm_layout(
    legend.bg.alpha = 0.5,
    legend.bg.color = "white",
    legend.position = c("right", "top"),
    legend.text.size= 0.5,
    legend.stack="horizontal")
```



#### Create bike flows and routes
```{r}
#Step 4 = for bike flows
#To avoid plotting 26000 lines we need to subset by bicycle
#select top all flows the mean is .37 and min is 0 max is 47
#select a new threshold for bicycle
bike_min <- 3
#define minimum trips for inter flows
bike.top <- lines.inter %>% filter (bicycle >= bike_min)
nrow(bike.top)
#define minimum trips for all flows
#bike.top.all  <- lines.lcr %>% filter (bicycle >= bike_min)

#Create a new threshold for 20 trips min
bike_20 <- lines.inter %>% filter (bicycle >= 10)
nrow(bike_20)
plot(bike_20$geometry)
#create top all commutes
#trips.all.min <- 20
#lines.all.top <- lines.inter %>% filter (all >= trips.all.min)
```

```{r}
summary(bike.top$bicycle)
```


```{r}
#Step 5
#plot with tmap top bike trajectories with min 3 trips
#tmap_mode("plot")
#bike.top = bike.top.all %>% 
#  arrange(bicycle) 
bike_all <- tm_shape(boundary) + tm_borders() + tm_fill("grey86")+
  tm_shape(bike.top) +
  tm_lines(palette = "plasma", breaks = c(3, 10, 20, 40, 50),
    lwd = "bicycle",
    #n=5,
    scale = 9,
    title.lwd = "Number of trips",
    alpha = 0.9,
    col = "bicycle",
    title = "Commutes by cycle",
    legend.lwd.show = FALSE) +
  tm_scale_bar(size=.5, width = 0.15,lwd= 0.3,
               position = c("left", "bottom"))+
   tm_compass(type = "arrow", size = 0.7, position = c("right", "bottom"))+
  tm_layout(
    legend.bg.alpha = 0.5,
    legend.bg.color = "white",
    legend.position = c("right", "top"),
    legend.text.size= 0.6,
    legend.stack="vertical")
bike_all
```

```{r}
getwd()
```


```{r}
#project
bike.top.pr = st_transform(bike.top, st_crs(boundary))
#save
st_write(bike.top.pr, "bike_top.shp", driver =  "ESRI Shapefile")
```



```{r}
#Step 6 convert OD lines to street level lines
bikes_net <- line2route(bike.top, route_fun = route_cyclestreet)
bikes_net_quiet <- line2route(bike.top, plan = "quietest")
bike_balance <- line2route(bike.top, plan= "balanced")
plot(bike_balance$geometry)
```

The created network need to be joined to the bike.top. First, create an id column for bike.top
```{r}
#Step 7a
#create id to join
bike.top <- bike.top %>% 
  mutate(id = row_number())
```

```{r}
#Step 7b
#save as table drop geometry
bike_nogeo <- bike.top %>%
  st_drop_geometry() %>%
  select(id,geo_code1, geo_code2, all, bicycle)
bikes_net <- bikes_net %>%
  select(id)
#create for quiet routes
#bikes_net_quiet <- bikes_net_quiet%>%
#  select(id)
#create for balanced routes
bike_balance <- bike_balance %>%
  select(id)
#Convert to numeric
bike_balance$id <- as.numeric(bike_balance$id)
```

```{r}
#Step 7c
#join all cycle network
#bike_network_all <- left_join(bikes_net, bike_nogeo)
#plot(bike_network_all$geometry)
#Join quiet routes
#bike_all_quiet <- left_join(bikes_net_quiet, bike_nogeo)
#plot(bike_all_quiet$geometry)
#join balanced routes
bike_balancenet <- left_join(bike_balance, bike_nogeo)
plot(bike_balancenet$geometry)
```

```{r}
#step 8
#create route network
#Summarize lines to network with overline2
#this results in a shape without any data, just lines
#bikes_routesnet <- overline2(x = bike_network_all, "bicycle")
#create netowrk for quiet
#bikes_routesquiet <- overline2(x= bike_all_quiet, "bicycle")
#create network for balanced
bikes_routesbalan <- overline2(x= bike_balancenet, "bicycle")
#plot
tm_shape(liv_shape)+tm_polygons()+
  tm_shape(bikes_routesbalan)+tm_lines(lwd = "bicycle", scale = 9, col = "bicycle" )
```

```{r}
#step 9
#create the same visualization as the OD map
#plot with tmap top bike trajectories with min 3 trips
bike_route <- tm_shape(boundary) + tm_borders() + tm_fill("grey86")+
  tm_shape(bikes_routesbalan) +
  tm_lines(palette = "plasma", breaks = c(3,15,30,50,100, 400),
    lwd = "bicycle",
    n=5,
    scale = 9,
    title.lwd = "Number of trips",
    alpha = 0.9,
    col = "bicycle",
    title = "Commutes by cycle",
    legend.lwd.show = FALSE) +
  tm_scale_bar(size=.5, width = 0.15,lwd= 0.3,
               position = c("left", "bottom"))+
   tm_compass(type = "arrow", size = 0.7, position = c("right", "bottom"))+
  tm_layout(
    legend.bg.alpha = 0.5,
    legend.bg.color = "white",
    legend.position = c("right", "top"),
    legend.text.size= 0.5,
    legend.stack="vertical")
bike_route
```

### Create no drive flow map
```{r}
#To avoid plotting 26000 lines we need to subset
#select top all flows the mean is 17 and min is 1 max is 965
#select a new threshold for all 
trips_all_min <- 50
#Select all flows according to the minimum set
lines.top <- lines.inter %>% filter (all >= trips_all_min)
#select both inter and intra regional with the minimum set
#top.intra.inter <- lines.lcr %>% filter(all>= 30)
nrow(lines.top)
nrow(lines.lcr)
#create percent that does not drive
lines.top$no_drive <- 100 - (lines.top$car_driver) / lines.top$all *100
```

```{r}
#re project
boundary <- st_read("LCR_Boundary.shp")
#project
lines_top_50 = st_transform(lines.top, st_crs(boundary))
#save
st_write(lines_top_50, "lines_top_50.shp", driver =  "ESRI Shapefile")
```


```{r}
#plot flows not by car
#lines.top = lines.top %>% 
 # arrange(no_drive) 
no_drive <- tm_shape(liv_shape) + tm_borders() +
  tm_shape(lines.top) +
  tm_lines(palette = "viridis", style = "pretty", n = 5,
    lwd = "all",
    scale = 9,
    title.lwd = "Number of trips",
    alpha = 0.5,
    col = "no_drive",
    title = "No car flows (%)",
    legend.lwd.show = TRUE) +
  tm_scale_bar(size = 0.3, width = 0.15,lwd= 0.3,
               position = c("left", "bottom")) +
  tm_compass(type = "arrow", size = 0.7, position = c("right", "bottom"))+
  tm_layout(
    legend.title.size = 0.6,
    legend.bg.alpha = 0.8,
    legend.bg.color = "white",
    #legend.position = c("right", "top"),
    #legend.height = 0.5,
    legend.text.size = 0.5,
    legend.stack="vertical",
    frame = TRUE,
    frame.lwd = 0.5,
    legend.show = TRUE,
    legend.width = 1)
no_drive
```

### Creating origin and destination zone maps
```{r}
#create origin zones
#group origins by msoa code
#get zones/MSOA areas
zones_liv = pct::get_pct_zones("liverpool-city-region") %>% 
  select("geo_code")
origin_attributes = lines.inter %>% 
  sf::st_drop_geometry() %>% 
  group_by(geo_code1) %>% 
  summarize_if(is.numeric, sum) %>% 
  dplyr::rename(geo_code = geo_code1)
# origin_attributes <-
origins = left_join(zones_liv, origin_attributes, by = "geo_code")
#Plot columns 4-14
plot(origins[c(4:14)], border = NA, max.plot=11)
```


```{r}
#Create map for origins top flows
origin_zone <- tm_shape(origins) + tm_fill("all", 
                             palette = "-viridis", n=5,
                             breaks = c(0,800,1500,2500,4000),
                             title = "Total trips")  +
  tm_borders(col = "grey", lwd = 0.3) + 
  tm_scale_bar(size = 0.4, width = 0.15 ,position = c("left", "bottom"))+
  tm_compass(type = "arrow", size = 0.7, position = c("right", "bottom"))+
  tm_layout(legend.position = c("right", "top"))
origin_zone
```

```{r}
#create destination zones
#group destination top flows by msoa
zones_liv = pct::get_pct_zones("liverpool-city-region") %>% 
  select("geo_code")
destination = lines.inter %>% 
  sf::st_drop_geometry() %>% 
  group_by(geo_code2) %>% 
  summarize_if(is.numeric, sum) %>%
  dplyr::rename(geo_code = geo_code2) %>% 
  #mutate_at(vars(-matches("geo_|all")), funs( . / all)) %>% 
left_join(zones_liv, ., by = "geo_code")
#plot columns 2-13
plot(destination[c(2:13)], border = NA, max.plot=12)
```

```{r}
#destination top flows
dest_zones <- tm_shape(destination) + tm_fill("all", 
                             palette = "-viridis", n=5,
                             breaks = c(0,600,1500,5000,10000,25000),
                             title = "Total trips")  +
  tm_borders(col = "grey", lwd = 0.5) + 
  tm_scale_bar(size = 0.3, width = 0.15 ,position = c("left", "bottom"))+
  tm_compass(type = "arrow", size = 0.5, position = c("right", "bottom"))+
  tm_layout(legend.position = c("right", "top"))
dest_zones
```

